services:
  postgres:
    image: postgres:18-alpine
    container_name: blockenfy-db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 3

  app:
    build: .
    container_name: blockenfy-app
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "pnpm run db:migrate && pnpm run dev"

volumes:
  pgdata:
